import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        // Stitch cyberpunk palette
        background: "#10141a",
        "surface-container-lowest": "#0a0e14",
        "surface-container-low": "#181c22",
        "surface-container": "#1c2026",
        "surface-container-high": "#262a31",
        "surface-container-highest": "#31353c",
        "surface-variant": "#31353c",
        "surface-bright": "#353940",
        "surface-dim": "#10141a",
        "on-surface": "#dfe2eb",
        "on-surface-variant": "#b9caca",
        "on-background": "#dfe2eb",
        "primary": "#e9feff",
        "primary-fixed": "#63f7ff",
        "primary-fixed-dim": "#00dce5",
        "on-primary-fixed": "#002021",
        "on-primary-fixed-variant": "#004f53",
        "on-primary-container": "#006c71",
        "primary-container": "#00f5ff",
        "inverse-primary": "#00696e",
        "inverse-surface": "#dfe2eb",
        "inverse-on-surface": "#2d3137",
        "surface-tint": "#00dce5",
        "secondary": "#44f6a3",
        "secondary-fixed": "#53ffac",
        "secondary-fixed-dim": "#20e291",
        "on-secondary-fixed": "#002111",
        "on-secondary-fixed-variant": "#005231",
        "on-secondary": "#003920",
        "secondary-container": "#00d98a",
        "on-secondary-container": "#005935",
        "tertiary": "#fff9f5",
        "tertiary-fixed": "#ffdea8",
        "tertiary-fixed-dim": "#ffba20",
        "on-tertiary-fixed": "#271900",
        "on-tertiary-fixed-variant": "#5e4200",
        "on-tertiary-container": "#805b00",
        "tertiary-container": "#ffd895",
        "on-tertiary": "#412d00",
        "error": "#ffb4ab",
        "error-container": "#93000a",
        "on-error": "#690005",
        "on-error-container": "#ffdad6",
        "outline": "#849495",
        "outline-variant": "#3a494a",
        // Legacy aliases (Jyra style) - use Stitch colors instead
        card: "#1c2026",
        border: "#31353c",
        accent: "#00f5ff",
        success: "#44f6a3",
        warning: "#ffba20",
        alert: "#ff4ab4",
      },
      fontFamily: {
        headline: ["Space Grotesk", "sans-serif"],
        body: ["Manrope", "sans-serif"],
        label: ["Space Grotesk", "sans-serif"],
        sans: ["Manrope", "system-ui", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"],
      },
      borderRadius: {
        DEFAULT: "0px",
        lg: "0px",
        xl: "0px",
        full: "9999px",
      },
    },
  },
  plugins: [],
};

export default config;
